INSERT INTO USER (ID, USERNAME, PASSWORD, ACTIVE, ROLES)
VALUES (1, 'admin', 'admin', true, 'ROLE_USER,ROLE_ADMIN');
INSERT INTO USER (ID, USERNAME, PASSWORD, ACTIVE, ROLES)
VALUES (2, 'user', 'pass', true, 'ROLE_USER');